//! # `Pin` and Why Rust Needs It
//! 
//! ## Interview Question
//! 
//! Explain `Pin` and Why Rust Needs It.
//! 
//! ## Interview Answer
//! 
//! > "Pin is a wrapper type that guarantees a value will not be moved in memory after it has been pinned. This is important for self-referential types, where one field stores a pointer or reference to another field within the same object.
//! >
//! > If such an object were moved, those internal references would become invalid, leading to undefined behavior. Pin prevents this by guaranteeing a stable memory location.
//! >
//! > In practice, Pin is most commonly used by Rust's async system because Futures generated by async functions may contain self-references. Tokio and async runtimes rely on Pin to safely poll Futures without moving them."
//! 
//! ---
//! 
//! ## Follow-up Questions & Answers
//! 
//! ### Q1. What is `Pin`?
//! 
//! **Interview Answer:**
//! 
//! > "`Pin` is a wrapper that guarantees a value will not be moved in memory after it has been pinned."
//! 
//! ---
//! 
//! ### Q2. Why do we need `Pin`?
//! 
//! **Interview Answer:**
//! 
//! > "We need `Pin` for types that rely on stable memory addresses, especially self-referential types and asynchronous Futures."
//! 
//! ---
//! 
//! ### Q3. What problem does `Pin` solve?
//! 
//! **Interview Answer:**
//! 
//! > "It prevents objects from being moved after internal references have been established, avoiding invalid pointers and undefined behavior."
//! 
//! ---
//! 
//! ### Q4. Why do async Futures require `Pin`?
//! 
//! **Interview Answer:**
//! 
//! > "Because compiler-generated Futures may contain self-references. `Pin` ensures the Future remains at a stable memory location while it's being polled."
//! 
//! ---
//! 
//! ### Q5. Does `Pin` make data immutable?
//! 
//! **Interview Answer:**
//! 
//! > "No. `Pin` only prevents movement. It doesn't prevent mutation if the type supports it."
//! 
//! ---
//! 
//! ### Q6. Is `Box<T>` automatically pinned?
//! 
//! **Interview Answer:**
//! 
//! > "No. `Box<T>` owns heap data, but the value can still be moved. `Box::pin()` creates a pinned heap allocation."
//! 
//! ---
//! 
//! ### Q7. Do application developers use `Pin` frequently?
//! 
//! **Interview Answer:**
//! 
//! > "Not usually. Most application code relies on libraries like Tokio, which manage `Pin` internally. It's more common when implementing custom async primitives or low-level libraries."
//! 
//! ---
//! 
//! ### Q8. What is a self-referential type?
//! 
//! **Interview Answer:**
//! 
//! > "A self-referential type contains references or pointers to its own fields. Moving the object would invalidate those references."
//! 
//! ---
//! 
//! ### Q9. What is the relationship between `Future` and `Pin`?
//! 
//! **Interview Answer:**
//! 
//! > "Async executors poll pinned Futures because pinning guarantees the Future won't move while it's suspended and resumed."
//! 
//! ---
//! 
//! ### Q10. Where have you encountered `Pin` in backend development?
//! 
//! **Interview Answer:**
//! 
//! > "Primarily in async programming with Tokio, custom Futures, stream implementations, and some networking libraries. Even if I don't use it directly every day, I understand that it's fundamental to Rust's async execution model."

pub const TOPIC: &str = "`Pin` and Why Rust Needs It";
